### ISSUE TITLE
NuGet client needs updating?

### ISSUE THREAD

**Issue by jbogard** [ServiceStack/Gistlyn#4]
If I try to install the latest AutoMapper package (which multi-targets), I get:

```
(InvalidOperationException) 'Microsoft.CSharp' already has a dependency defined for 'System.Dynamic.Runtime'.
```

This is usually because of an old NuGet client (2.x vs 3.4.x)

**Comment by mythz** [comment]
Cool thx for the pointer, I'll try upgrading the NuGet.Core dependency to see if it helps.

Unfortunately I'm in the middle of an upgrading ServiceStack to VS2017 where I don't have VS2015 installed on my main dev MBP and trying to open Gistlyn in an older dev pc with VS2015 installed has resulted in a large number of npm/typescript errors due to bitrot from npm dep versions. 

I'll look into upgrading Gistlyn to latest VS2017 w/ latest npm deps after I'm on the other side of this VS 2017 migration.

**Comment by mythz** [comment]
ok that was slightly painful, upgrading to latest `"Microsoft.CodeAnalysis.CSharp.Scripting` v2 fails with [Could not load file or assembly System.IO.FileSystem, Version=4.0.1.0](http://stackoverflow.com/q/41979136/85785) which no combination of binding redirects seems to resolve, so had to revert to latest `v1.2.1` that worked. 

Upgrading npm deps breaks everything. Latest [VS 2017 only has TypeScript 2.1.5](https://blogs.msdn.microsoft.com/typescript/2017/03/27/typescripts-new-release-cadence/) meanwhile everywhere else has v2.2 which has `fetch` TypeScript definitions built-in so VS can't find fetch type definitions and when they're explicitly imported from `@types/whatwg-fetch` VS Code fails to build with dupe type defs so ended up disabling TypeScript builds failing in VS 2017. Then the latest JSPM doesn't work with TypeScript so ended up converting everything over to Webpack.

But the solution to this issue itself wasn't too bad, except the `Mono.NuGet.Core` NuGet package we were using is no longer maintained so had to switch to latest `NuGet.Core` which resolved this issue at the expense of Gistlyn no longer running on Mono, but it's time to say goodbye to Mono anyway.

But at the end you should now be able to reference AutoMapper NuGet package from http://gistlyn.com :)

**Comment by jbogard** [comment]
Awesome, thanks!
